import { session } from "electron";

const BROWSER_PARTITION = "persist:superset";

/**
 * The frozen platform token real desktop Chrome sends per OS. Chrome stopped
 * exposing the actual OS version in the UA (macOS is pinned to 10_15_7 even on
 * Apple Silicon, Windows to NT 10.0), so these literals are what an ordinary
 * Chrome install reports today.
 */
function chromePlatformToken(): string {
	switch (process.platform) {
		case "darwin":
			return "Macintosh; Intel Mac OS X 10_15_7";
		case "win32":
			return "Windows NT 10.0; Win64; x64";
		default:
			return "X11; Linux x86_64";
	}
}

/**
 * A user-agent string matching what real desktop Chrome sends on this OS for
 * the Chromium bundled with this Electron build. The major version comes from
 * `process.versions.chrome` — never hardcode one: Client Hints (`sec-ch-ua`,
 * `navigator.userAgentData`) are generated by the engine itself, and a UA
 * claiming a different version than the hints report is a stronger bot signal
 * than no override at all. Real Chrome's UA is version-reduced to
 * `<major>.0.0.0` (the full build number only appears in Client Hints), so
 * ours is too.
 */
export function buildChromeUserAgent(): string {
	const chromeMajor = process.versions.chrome.split(".")[0];
	return `Mozilla/5.0 (${chromePlatformToken()}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${chromeMajor}.0.0.0 Safari/537.36`;
}

/**
 * Make the browser pane's session fingerprint as ordinary Chrome. Electron's
 * default UA appends `Electron/x.y.z` and the app's product name — an
 * immediate tell to bot-detection scripts (Cloudflare, DataDome, …) that can
 * get a user's own ordinary browsing wrongly challenged or blocked.
 */
export function configureBrowserUserAgent(): void {
	session.fromPartition(BROWSER_PARTITION).setUserAgent(buildChromeUserAgent());
}
