import { homedir } from "node:os";
import { join } from "node:path";

/** Mount target for the generated container superset-home (read-only). */
export const CONTAINER_SUPERSET_DIR = "/opt/superset";
/** Mount target for the per-workspace isolated git dir. */
export const CONTAINER_GIT_DIR = "/sandbox/git";
/** Mount target for the per-workspace host-access dir (CLI token). */
export const CONTAINER_HOST_DIR = "/sandbox/host";
/** In-container SUPERSET_HOME_DIR contents live under CONTAINER_SUPERSET_DIR. */
export const CONTAINER_BASH_RCFILE = `${CONTAINER_SUPERSET_DIR}/bash/rcfile`;

export function getSupersetHomeDir(): string {
	return process.env.SUPERSET_HOME_DIR || join(homedir(), ".superset");
}

/** Root for all host-side sandbox state. */
export function getSandboxRootDir(): string {
	return join(getSupersetHomeDir(), "sandbox");
}

/**
 * Host-side directory generated by sandbox-home.ts and bind-mounted
 * read-only at CONTAINER_SUPERSET_DIR in every sandbox container.
 */
export function getSandboxHomeDir(): string {
	return join(getSandboxRootDir(), "home");
}

export interface WorkspaceSandboxPaths {
	/** Per-workspace state root; removed on workspace delete. */
	stateDir: string;
	/** Isolated git dir bind-mounted at CONTAINER_GIT_DIR. */
	gitDir: string;
	/** One-line mask bind-mounted read-only over <worktree>/.git. */
	dotGitFile: string;
	/** HEAD sha the sandbox git dir was bootstrapped from. */
	bootstrapShaFile: string;
}

export function getWorkspaceSandboxPaths(
	workspaceId: string,
): WorkspaceSandboxPaths {
	const stateDir = join(getSandboxRootDir(), "workspaces", workspaceId);
	return {
		stateDir,
		gitDir: join(stateDir, "git"),
		dotGitFile: join(stateDir, "dot-git"),
		bootstrapShaFile: join(stateDir, "bootstrap-sha"),
	};
}

export function getSandboxContainerName(workspaceId: string): string {
	return `superset-ws-${workspaceId}`;
}
